name: {{ cookiecutter.project_slug }}
targets:
  {{ cookiecutter.project_slug }}:
    platform: iOS
    type: framework
    sources:
      - Sources/
  {{ cookiecutter.project_slug }}Tests:
    platform: iOS
    type: bundle.unit-test
    sources:
      - Tests/
    dependencies:
      - target: {{ cookiecutter.project_slug }}
    scheme:
      testTargets:
        - {{ cookiecutter.project_slug }}Tests
      gatherCoverageData: true